
// This file has been generated by the GUI designer. Do not modify.
namespace VolatileReader
{
	public partial class LegacyEventLogReader
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VolatileReader.LegacyEventLogReader
			this.Name = "VolatileReader.LegacyEventLogReader";
			this.Title = global::Mono.Unix.Catalog.GetString ("LegacyEventLogReader");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
