
// This file has been generated by the GUI designer. Do not modify.
namespace VolatileRegistryReader
{
	public partial class NodeKeyInfo
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget VolatileRegistryReader.NodeKeyInfo
			this.Name = "VolatileRegistryReader.NodeKeyInfo";
			this.Title = global::Mono.Unix.Catalog.GetString ("NodeKeyInfo");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 400;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
